### ISSUE TITLE
Cannot use Global and workspace commandbar settings simultaneously

### ISSUE THREAD

**Issue by ArturoRis** [ppatotski/vscode-commandbar#65]
I set a global commandbar.json then if I set a commandbar.json for the current workspace the latter override the first.
It should be possible to use both simultaneously adding the workspace commands to the one listed in the global settings

**Comment by Zyrsha** [comment]
Same problem here.

The command bar should be capable of loading ~/.vscode/commandbar.json and also ./.vscode/commandbar.json sequentially, so that global commands can combine with project-specific commands.

It only took a few minutes to get around the problem, but I had to clone and modify the commandbar extension in order to run 2 copies of it. Just change the config file and pathnames in your 2nd copy, and make it use a unique extension id. Then it will combine the two bars from each extension.

**Comment by Zyrsha** [comment]
Btw, it works very nicely with global + workspace commandbars because the priority system allows them to merge together perfectly into one bar.

**Comment by ppatotski** [comment]
Thanks guys! Check out the new version.

**Comment by Zyrsha** [comment]
Thank you very much. It works perfectly. Very good.
